### PR TITLE
Fix @SecondTuesdayOfMonth and change logic for pulling rollups

### PR DESCRIPTION
**Pull request by Madj42**
Fixed @SecondTuesdayOfMonth and change logic for pulling the current and last rollups.

### CODE REVIEW

**Comment by Madj42** [comment]
This is the corrected pull request.

**Comment by Madj42** [comment]
I'm not really sure why I was having issues with the second Tuesday query but today it's working with the original version.  So I guess you can take that with a grain of salt.  I still however think the other part of the changes are beneficial as it makes the compliance percentages more accurate based on the time of month and they do not stop working on the first of the month before patch Tuesday.

**Comment by jonasatgit** [comment]
Hi @Madj42 thank you for your contribution. I haven't had time to look into it yet but will do asap. 
Best regards 
Jonas

**Comment by Madj42** [comment]
No problem.  Thank you so much for the awesome report.  I love using this
and promoting this for our techs to troubleshoot issues.

**Review by jonasatgit — APPROVED** [review]
Thank you for your contribution. Highly appreciated. 
I will update the whole solution in the next couple of days to introduce some more changes and will update the blog article to reflect that. 
Best regards
Jonas

**Pull request merged**
